name: init

on: 

# Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:

  call-workflow-A:
    uses: .github/workflows/createTemplate.yml@main
    with:
      username: Houssem
